# Generated by Django 2.1.7 on 2019-03-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='link_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
